### ISSUE TITLE
Gigazineで見ました。

### ISSUE THREAD

**Issue by matyapiro31** [hogesuke/ika-shot#1]
ラズパイでビルドされたとのことですが、
qemu-debootstrapを使えばx64でビルドできますよ。

**Comment by hogesuke** [comment]
情報ありがとうございます！
そういうものがあったんですね、知りませんでした。

次、マシンパワー必要そうなビルドをするときは使ってみます :smile:

**Comment by matyapiro31** [comment]
http://qiita.com/matyapiro31/items/763493e390e58b024ea3
書いておきました。

**Comment by hogesuke** [comment]
ありがとうございます！すごく助かります！
